# Generated by Django 5.0.2 on 2024-04-17 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffConnectAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_broker', models.CharField(max_length=50)),
                ('s_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('s_client_id', models.CharField(max_length=100)),
                ('s_pin', models.CharField(max_length=10)),
                ('s_qr_value', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=255)),
                ('s_fetched_data', models.JSONField(blank=True, null=True)),
                ('s_balance_data', models.JSONField(blank=True, null=True)),
                ('s_trade_data', models.JSONField(blank=True, null=True)),
                ('s_option_data', models.JSONField(blank=True, null=True)),
                ('s_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
