# Generated by Django 5.0.2 on 2024-04-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffconnectapi',
            old_name='s_user',
            new_name='user',
        ),
    ]
