# Generated by Django 5.0.2 on 2024-04-17 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_s_user_staffconnectapi_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffClientAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('qr_value', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=255)),
                ('fetched_data', models.JSONField(blank=True, null=True)),
                ('balance_data', models.JSONField(blank=True, null=True)),
                ('trade_data', models.JSONField(blank=True, null=True)),
                ('option_data', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
