# Generated by Django 5.0.2 on 2024-04-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffclientadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffclientadd',
            old_name='user',
            new_name='s_client_user',
        ),
    ]
