# Generated by Django 4.1 on 2023-12-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_profile_image',
            field=models.ImageField(default='images/Angel_ONe.png', null=True, upload_to='profile_images/'),
        ),
    ]
