# Generated by Django 4.1 on 2023-12-08 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_staffprofile_staff_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_profile_image',
            field=models.ImageField(default='images/Angel_ONe.png', null=True, upload_to='Staff_images/'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_profile_image', models.ImageField(default='images/Angel_ONe.png', null=True, upload_to='client_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
