# Generated by Django 4.1 on 2023-12-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_staffprofile_staff_profile_image_clientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='user',
            new_name='user_client',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='user',
            new_name='user_staff',
        ),
    ]
