# Generated by Django 4.1 on 2023-12-15 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0004_rename_user_clientprofile_user_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_profile_image', models.ImageField(default='images/Angel_ONe.png', null=True, upload_to='finance_images/')),
                ('user_finance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
