# Generated by Django 4.1 on 2023-12-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_financeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
            ],
        ),
    ]
