# Generated by Django 4.1 on 2024-01-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
