# Generated by Django 5.0.2 on 2024-04-01 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_delete_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClientadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('qr_value', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=255)),
                ('fetched_data', models.JSONField(blank=True, null=True)),
                ('balance_data', models.JSONField(blank=True, null=True)),
                ('trade_data', models.JSONField(blank=True, null=True)),
                ('option_data', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterConnectAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_broker', models.CharField(max_length=50)),
                ('m_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('m_client_id', models.CharField(max_length=100)),
                ('m_pin', models.CharField(max_length=10)),
                ('m_qr_value', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=255)),
                ('m_fetched_data', models.JSONField(blank=True, null=True)),
                ('m_balance_data', models.JSONField(blank=True, null=True)),
                ('m_trade_data', models.JSONField(blank=True, null=True)),
                ('m_option_data', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
