# Generated by Django 4.1 on 2023-12-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAccount',
            new_name='MasterAccount',
        ),
    ]
