# Generated by Django 4.1 on 2023-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_masteraccount_groups_masteraccount_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteraccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='master_username',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='masteraccount',
            name='username',
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6),
        ),
    ]
