# Generated by Django 4.1 on 2023-12-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_masteraccount_user_alter_masteraccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteraccount',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='nominee_relationship',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
