# Generated by Django 4.1 on 2023-12-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_masteraccount_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masteraccount',
            old_name='user',
            new_name='user_master',
        ),
    ]
