# Generated by Django 4.1 on 2024-01-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0009_alter_clientaccount_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_full_name', models.CharField(blank=True, max_length=255)),
                ('staff_profile_image', models.ImageField(blank=True, null=True, upload_to='staff_profile_images/')),
                ('staff_date_of_birth', models.DateField(blank=True, null=True)),
                ('staff_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('staff_phone', models.CharField(blank=True, max_length=15)),
                ('staff_email', models.EmailField(blank=True, max_length=254)),
                ('staff_address', models.TextField(blank=True)),
                ('staff_pincode', models.CharField(blank=True, max_length=10)),
                ('staff_district', models.CharField(blank=True, max_length=255)),
                ('staff_state', models.CharField(blank=True, max_length=255)),
                ('staff_occupation', models.CharField(blank=True, max_length=255)),
                ('staff_parent_name', models.CharField(blank=True, max_length=255)),
                ('staff_nominee_name', models.CharField(blank=True, max_length=255)),
                ('staff_nominee_relationship', models.CharField(blank=True, max_length=255)),
                ('user_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
